# Generated by Django 4.2.6 on 2023-11-06 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_composite_auto_field.fields
import django_countries.fields
import dynamic_filenames
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, default=' ', max_length=100)),
                ('Amount', models.IntegerField()),
                ('Donation_type', models.CharField(choices=[('Iftaresaim', 'Iftaresaim'), ('Ouduhuya', 'Ouduhuya'), ('Mesjid', 'Mesjid'), ('Quran', 'Quran'), ('ZekatelFiter', 'ZekatelFiter'), ('Mesakin', 'Mesakin'), ('Education', 'Education')], default='Quran', max_length=20)),
                ('Donation_attachment', models.FileField(default='', upload_to=dynamic_filenames.FilePattern(filename_pattern='{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'))),
                ('upload_finished_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='IslamicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('Location', models.CharField(max_length=255)),
                ('Organizer', models.CharField(max_length=255)),
                ('File', models.FileField(upload_to='eventfile/')),
                ('Uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'islamicevents',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', django_composite_auto_field.fields.CompositeAutoField(editable=False, max_length=250, prefix='GAIA', use_year=False, zeros=5)),
                ('Fullname', models.CharField(blank=True, default=' ', max_length=100)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ET')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Email', models.EmailField(blank=True, default=' ', max_length=254)),
                ('Joined_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.CharField(default=' ', max_length=50, primary_key='true', serialize=False, unique='true')),
                ('Pname', models.CharField(blank=True, default=' ', max_length=100)),
                ('Location', models.CharField(blank=True, default=' ', max_length=100)),
                ('Allocated_Budget', models.IntegerField(blank=True, default=0, null=True)),
                ('Start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('End_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PFile', models.FileField(upload_to='projectfile/')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, default=' ', max_length=100)),
                ('Year', models.IntegerField(default=2023)),
                ('January', models.IntegerField(blank=True, default=0, null=True)),
                ('February', models.IntegerField(blank=True, default=0, null=True)),
                ('March', models.IntegerField(blank=True, default=0, null=True)),
                ('April', models.IntegerField(blank=True, default=0, null=True)),
                ('May', models.IntegerField(blank=True, default=0, null=True)),
                ('June', models.IntegerField(blank=True, default=0, null=True)),
                ('July', models.IntegerField(blank=True, default=0, null=True)),
                ('August', models.IntegerField(blank=True, default=0, null=True)),
                ('September', models.IntegerField(blank=True, default=0, null=True)),
                ('October', models.IntegerField(blank=True, default=0, null=True)),
                ('November', models.IntegerField(blank=True, default=0, null=True)),
                ('December', models.IntegerField(blank=True, default=0, null=True)),
                ('Total', models.IntegerField(blank=True, default=0, null=True)),
                ('DMID', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='GICA.member')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
