# Generated by Django 4.2.6 on 2023-11-10 05:06

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('GICA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorNiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, default=' ', max_length=100)),
                ('Amount', models.IntegerField()),
                ('Donation_type', models.CharField(choices=[('Iftaresaim', 'Iftaresaim'), ('Ouduhuya', 'Ouduhuya'), ('Mesjid', 'Mesjid'), ('Quran', 'Quran'), ('ZekatelFiter', 'ZekatelFiter'), ('Mesakin', 'Mesakin'), ('Education', 'Education')], default='Quran', max_length=20)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ET')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'db_table': 'donorniya',
            },
        ),
        migrations.AddField(
            model_name='donor',
            name='Country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ET'),
        ),
    ]
